package online.draran.billing.core.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Brand palette: indigo primary, saffron accent, emerald for money received.
// Chosen to stand apart from the red/blue used by most Indian billing apps.

internal val LightColors = lightColorScheme(
    primary = Color(0xFF4F46E5),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE0E7FF),
    onPrimaryContainer = Color(0xFF1E1B6B),
    inversePrimary = Color(0xFFA5B4FC),
    secondary = Color(0xFF5C5D8D),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE3E1FF),
    onSecondaryContainer = Color(0xFF191A45),
    tertiary = Color(0xFFB45309),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFEDD5),
    onTertiaryContainer = Color(0xFF431407),
    error = Color(0xFFDC2626),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFEE2E2),
    onErrorContainer = Color(0xFF7F1D1D),
    background = Color(0xFFF7F7FB),
    onBackground = Color(0xFF14142B),
    surface = Color(0xFFF7F7FB),
    onSurface = Color(0xFF14142B),
    surfaceVariant = Color(0xFFE6E6F0),
    onSurfaceVariant = Color(0xFF5A5A72),
    surfaceTint = Color(0xFF4F46E5),
    inverseSurface = Color(0xFF2A2A40),
    inverseOnSurface = Color(0xFFF1F1F8),
    outline = Color(0xFF8E8EA6),
    outlineVariant = Color(0xFFDCDCE8),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFDCDCE6),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF2F2F9),
    surfaceContainer = Color(0xFFEDEDF6),
    surfaceContainerHigh = Color(0xFFE7E7F1),
    surfaceContainerHighest = Color(0xFFE1E1EC),
)

internal val DarkColors = darkColorScheme(
    primary = Color(0xFFA5B4FC),
    onPrimary = Color(0xFF1E1B6B),
    primaryContainer = Color(0xFF3730A3),
    onPrimaryContainer = Color(0xFFE0E7FF),
    inversePrimary = Color(0xFF4F46E5),
    secondary = Color(0xFFC5C4F0),
    onSecondary = Color(0xFF2E2F5C),
    secondaryContainer = Color(0xFF444574),
    onSecondaryContainer = Color(0xFFE3E1FF),
    tertiary = Color(0xFFFDBA74),
    onTertiary = Color(0xFF431407),
    tertiaryContainer = Color(0xFF7C2D12),
    onTertiaryContainer = Color(0xFFFFEDD5),
    error = Color(0xFFF87171),
    onError = Color(0xFF450A0A),
    errorContainer = Color(0xFF7F1D1D),
    onErrorContainer = Color(0xFFFEE2E2),
    background = Color(0xFF0F0F1A),
    onBackground = Color(0xFFE6E6F2),
    surface = Color(0xFF0F0F1A),
    onSurface = Color(0xFFE6E6F2),
    surfaceVariant = Color(0xFF2A2A3C),
    onSurfaceVariant = Color(0xFFB4B4C8),
    surfaceTint = Color(0xFFA5B4FC),
    inverseSurface = Color(0xFFE6E6F2),
    inverseOnSurface = Color(0xFF1A1A2A),
    outline = Color(0xFF7A7A92),
    outlineVariant = Color(0xFF34344A),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF2E2E42),
    surfaceDim = Color(0xFF0F0F1A),
    surfaceContainerLowest = Color(0xFF0A0A14),
    surfaceContainerLow = Color(0xFF161624),
    surfaceContainer = Color(0xFF1A1A2A),
    surfaceContainerHigh = Color(0xFF232335),
    surfaceContainerHighest = Color(0xFF2C2C40),
)
